services:
  - type: web
    name: utsavmunch-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_uri
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1 